### ISSUE TITLE
修正最新消息分類文字

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#1]
原本最新消息分類有消息、活動、最新訊息。請將【消息】改為【公告】

**Comment by EvelynHsiao** [comment]
![image](https://github.com/user-attachments/assets/f901294b-8623-4880-8961-6d6f0e5635ae)

**Comment by L-M-Jay** [comment]
已經修改

**Comment by mar50868** [comment]
測試無誤，結案
