### ISSUE TITLE
test1

### ISSUE THREAD

**Issue by pts-jon** [M-Jay-Liu/HakkaTV-Repair-Order#17]
![Public_Television_Service_Foundation_Logo](https://github.com/user-attachments/assets/60412b08-e760-4bff-9ee1-f9ef1de1c2bd)

**Comment by pts-jon** [comment]
![Cat03](https://github.com/user-attachments/assets/d113caac-373c-48a0-a7a2-5db2eb995da9)

**Comment by pts-jon** [comment]
![Cat03](https://github.com/user-attachments/assets/51e194b3-1d18-455b-a458-a7320ec7b677)

**Comment by pts-jon** [comment]
![Yahoo-TW-desktop-FP@2x](https://github.com/user-attachments/assets/5805ff79-80bb-49c2-be84-0be2287bdaec)

**Comment by mar50868** [comment]
![國際新聞-客觀世界第218集 mp4_20240813_134252 344](https://github.com/user-attachments/assets/c160f61d-0591-41a7-b991-e2c1cf38b261)

**Comment by HakkaTV-Sue** [comment]
![Uploading 螢幕擷取畫面 2024-08-20 104158.png…]()

**Comment by HakkaTV-Sue** [comment]
![螢幕擷取畫面 2024-08-20 104158](https://github.com/user-attachments/assets/d36b990a-3e11-4350-bb71-cde2301e6cdc)
