### ISSUE TITLE
關於客服留言部分，無法送出

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#2]
有網友反應
當在填寫客服意見時
https://www.hakkatv.org.tw/service/audience/custom-service
無法送出申請
但經過F5重整
就可以送出
請協助檢測是否相關問題產生

**Comment by M-Jay-Liu** [comment]
目前測試功能正常
推測應該是用戶填寫Email的時候可能不小心填寫錯誤沒有依照格式填寫，所以送出按鈕會不讓他按，重新整理後正確填寫Email就可以成功送出了。
