### ISSUE TITLE
左箭頭後 Banner 無法成功觸發圖片連結

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#20]
開始首頁模式，點選左鍵圖片時，無法成功觸發圖片連結
![image](https://github.com/user-attachments/assets/8b1c41f9-e53e-4e1f-940c-7a4dfcd7b9be)

https://github.com/user-attachments/assets/fee6bcbf-72b5-459f-81b9-a0981f2699d4

**Comment by M-Jay-Liu** [comment]
@mar50868 已經調整 再請確認

**Comment by mar50868** [comment]
修正功能測試成功，結案
