### ISSUE TITLE
APP IOS 影集代表圖 gif 無法正常顯示

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#21]
APP IOS 影集代表圖 gif 無法正常顯示
![image](https://github.com/user-attachments/assets/82313bb3-8126-44a5-867e-0be443f58c10)

**Comment by M-Jay-Liu** [comment]
@mar50868 因近期IOS系統更新，這邊需要將套件更新，GIF才能正常顯示
目前工程已經調整中，調整好後會再回覆給您

**Comment by M-Jay-Liu** [comment]
@mar50868 目前已經送審  等APP Store審核通過會再通知您

**Comment by mar50868** [comment]
測試顯示正常，可結案
