### ISSUE TITLE
有關客庄走透透與新聞側錄，側錄影片沒有自帶影集代表圖

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#25]
有關【客庄走透透】側錄影片如同三節新聞側錄，若無縮圖，應該自帶該節目影集代表圖或是客台LOGO縮圖
![image](https://github.com/user-attachments/assets/329fc99f-bc15-472d-b3d8-e1e211a44eba)

![image](https://github.com/user-attachments/assets/2d18889b-7359-4cbd-a39d-0a607f894596)

**Comment by M-Jay-Liu** [comment]
好的

**Comment by M-Jay-Liu** [comment]
已經調整沒有圖片的分集在選擇集數的位置會顯示預設LOGO圖片

**Comment by mar50868** [comment]
確認有正常顯示圖片，結案
![image](https://github.com/user-attachments/assets/abf91942-db78-4c80-b176-f7f5194c0abc)
****
