### ISSUE TITLE
為您推薦影集圖片無顯示

### ISSUE THREAD

**Issue by Brianhakka** [M-Jay-Liu/HakkaTV-Repair-Order#26]
![image](https://github.com/user-attachments/assets/9e32d5f3-3757-46ef-a13c-4b20758b9686)

**Comment by M-Jay-Liu** [comment]
已經調整沒有圖片的影集在推薦影片會顯示預設LOGO圖片

**Comment by mar50868** [comment]
已確認顯示正常，結案。
