### ISSUE TITLE
請協助確認首頁【熱門影音】排行是否失效?

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#27]
![image](https://github.com/user-attachments/assets/6a907dc4-e015-4b85-9c4a-bb825ccadbcd)
請確認熱門影音排行是否失效?
另外請教熱門影音的更動頻率是多長?是即時?每日?每週?

**Comment by M-Jay-Liu** [comment]
@mar50868 哥  已經請工程確認  應該是這個Google platform的這個帳號被刪掉ga-report@hakkatv.iam.gserviceaccount.com，導致要更新GA資料時失，這部分麻煩幫我確認一下能否復原該帳號或是提供新的Key給我們 感謝

**Comment by M-Jay-Liu** [comment]
已經確定是有人把ga-report@hakkatv.iam.gserviceaccount.com 這個帳號刪除導致，目前已經加回來 功能已經正常  熱門影音的更新頻率是每周一次

**Comment by mar50868** [comment]
測試正常，結案
