### ISSUE TITLE
策展版型C bug 

### ISSUE THREAD

**Issue by Brianhakka** [M-Jay-Liu/HakkaTV-Repair-Order#28]
![image](https://github.com/user-attachments/assets/7f6230e2-afca-45c1-91ad-6f1263a626f9)

**Comment by M-Jay-Liu** [comment]
好的 收到

**Comment by M-Jay-Liu** [comment]
已經調整完成 在請確認 感謝

**Comment by mar50868** [comment]
確認修復完畢，可結案
