### ISSUE TITLE
關於策展B、D版型問題

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#29]
舊版型未調整符合guideline
版型B：文字設定為調整(文字大小、行距)，請比照首頁其他版型的標題內文，且手機板文字區塊高度不一。
版型D 文字未設定上限2行

![image](https://github.com/user-attachments/assets/f5cfe658-e657-41da-a31e-17c4db69c11f)

![image](https://github.com/user-attachments/assets/1711d096-aad0-43ff-aaaf-9d036b0f6886)

**Comment by M-Jay-Liu** [comment]
已經更新到測試機了 在麻煩幫我確認一下調整是否可以  沒有問題的話我們就會上到正式機

![image](https://github.com/user-attachments/assets/6b667289-2244-410f-a811-971119b4f897)

紅色部分是版型B  橘色部分是版型D

**Comment by mar50868** [comment]
![image](https://github.com/user-attachments/assets/59ccc73a-1048-410c-b3e7-290a81e8bb1a)
![image](https://github.com/user-attachments/assets/6a644020-6708-4e91-a5c7-c6e735cebfdd)
測試完畢，結案
