### ISSUE TITLE
google 翻譯 live streaming L S大寫

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#30]
google 翻譯 live streaming L S大寫
請盡速處理
![image](https://github.com/user-attachments/assets/5bab1faa-95e3-4b33-9deb-5fd834b3ef2e)

**Comment by M-Jay-Liu** [comment]
https://hakkatv.dgfactor.com/
目前已經修改到測試機  因為Google自動翻譯無法進行調整 我們改於翻譯過後再次覆蓋翻譯結果的方式來調整 這部分麻煩幫我們確認一下這樣的呈現方式是否可以 沒有問題的話我們馬上上道正式機

**Comment by mar50868** [comment]
測試機顯示正常，請上正式機

**Comment by M-Jay-Liu** [comment]
已經上線

**Comment by mar50868** [comment]
![image](https://github.com/user-attachments/assets/b74a87e3-9af2-4c72-866c-a71ee38e67f1)
確認修正無誤
結案
