### ISSUE TITLE
兒少首頁策展出現BUG，缺少文字顯示

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#31]
![image](https://github.com/user-attachments/assets/b00190c1-c239-4631-8a85-71e601d1d367)
![image](https://github.com/user-attachments/assets/e95fcad6-4216-4dd9-a49e-08779efe9ca1)

**Comment by M-Jay-Liu** [comment]
已經調整

**Comment by mar50868** [comment]
![image](https://github.com/user-attachments/assets/4aa6da1b-ba4b-470f-b96c-a378d7c61ac1)
確認修正無誤，結案
