### ISSUE TITLE
關於Google線上轉譯英文版

### ISSUE THREAD

**Issue by mar50868** [M-Jay-Liu/HakkaTV-Repair-Order#8]
關於Google線上轉譯英文版
關於標題顯示
因為大部分是正常顯示單字第一個為大寫
例如：Live Streaming 、下面的Reasoning 字首改大寫
可以修正嗎?
https://drive.google.com/file/d/1guMyR0fnY4EhvqnEFtijGSAl90XvNHGy/view?usp=sharing

**Comment by M-Jay-Liu** [comment]
因為這是使用自動翻譯的套件，目前已經請工程去確認相關元件的文件 看是否有機會如你們這邊提出的需求去顯示

**Comment by L-M-Jay** [comment]
@mar50868 轉譯英文版的部分已經文件確認  因為是Google自動偵測進行翻譯 好像沒有任何方法可以調整大小寫
